def perform_operations(num1, num2):
    print(f"Addition: {num1 + num2}")
    print(f"Subtraction: {num1 - num2}")
    print(f"Multiplication: {num1 * num2}")
    print(f"Division: {num1 / num2}")
    print(f"Integer Division: {num1 // num2}")
    print(f"Floor Division: {num1 // num2}")
int1 = int(input("Enter the first integer: "))
int2 = int(input("Enter the second integer: "))
float1 = float(input("Enter the first float: "))
float2 = float(input("Enter the second float: "))
print("\nInteger Operations Results:")
perform_operations(int1, int2)
print("\nFloat Operations Results:")
perform_operations(float1, float2)
